repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.3.0'
  hooks:
  - id: check-merge-conflict
- repo: https://github.com/pycqa/isort
  rev: '5.6.4'
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: '20.8b1'
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.3.0'
  hooks:
  - id: end-of-file-fixer
    exclude: >-
      ^docs/[^/]*\.svg$
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.4'
  hooks:
  - id: flake8
    exclude: "^docs/"
- repo: git://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^[^/]+[.]rst$
