version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: ['make', "server"]
  db:
    image: mongo:4.4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DYNACONF_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DYNACONF_DB_PASSWORD}
