version: "3"

services:
  mongo:
    image: "mongo:4.4.0"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DYNACONF_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DYNACONF_DB_PASSWORD}
  redis:
    image: "redis:alpine"
  app:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    command: ['make', "server"]
