version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    restart: on-failure

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - pt-data:/data/mongo

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - pt-data:/data/redis
    env_file:
      - .env

volumes:
  pt-data:
