[default]
project_name = "Paper Trading"
description = "专注于证券市场模拟交易后台服务，交易市场可扩展。"
version = "2.0.1"
api_prefix = "/api"
base_url = "@format http://{env[DYNACONF_PT_HOST]}:{env[DYNACONF_PT_PORT]}/"

    # 数据库相关配置
    [default.db]
    host = "localhost"
    port = 27017
    url = "@format mongodb://{env[DYNACONF_DB_USER]}:{env[DYNACONF_DB_PASSWORD]}@{this.DB.HOST}:{this.DB.PORT}"
    name = "paper_trading"
    max_connections = 50
    min_connections = 10

    # Redis
    [default.redis]
    host = "127.0.0.1"
    port = 6379
    encoding = "utf-8"
    entrust_db = 1                  # 行情库
    base_url = "@format redis://{this.REDIS.HOST}:{this.REDIS.PORT}"
    entrust_url = "@format {this.REDIS.BASE_URL}/{this.REDIS.ENTRUST_DB}"

    # 数据库表名
    [default.db.collections]
    user = "users"
    order = "orders"

    # 日志
    [default.log]
    level = 10                      # 10 = DEBUG
    active = true

    # 服务
    [default.service]
    event_log = "e_log"
    event_error = "e_error"
    persistence_mode = "realtime"   # 数据持久化模式
    market = "china_a"              # 市场


[development]
    # 引擎
    [development.engine]
    persistence_mode = "manual"     # 数据持久化模式

[production]
    # 日志
    [production.log]
    level = 20                      # 20 = INFO

[testing]
    # 数据库相关配置
    [testing.db]
    name = "test_paper_trading"
