# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ paper_trading_v2 ]
  pull_request:
    branches: [ paper_trading_v2 ]

jobs:
  test:
    env:
      DYNACONF_PT_HOST: 127.0.0.1
      DYNACONF_PT_PORT: 5002
      DYNACONF_QUOTES_API: TDX
      DYNACONF_SECRET_KEY: secret_key
      DYNACONF_ALGORITHM: HS256
      DYNACONF_ACCESS_TOKEN_EXPIRE_MINUTES: 10080
      DYNACONF_TOKEN_PREFIX: Token
      DYNACONF_ENV_FOR_DYNACONF: production
      DYNACONF_DB_USER: mongo
      DYNACONF_DB_PASSWORD: mongo
      DYNACONF_AUTH_MODE: JWT
    name: Test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4.0
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests with pytest
      run: |
        poetry run pytest --cov=app --cov=tests --cov-report=term-missing --cov-config=setup.cfg \
        --cov-report=xml --cov-fail-under=90
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
      env:
        TOKEN: ${{ secrets.CODECOV_TOKEN }}
        REF: ${{ github.ref }}
